---
- name: Ensure Virtual Machines Exists
  azure_rm_virtualmachine:
    tenant: "{{ azure_tenant_id }}"
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_client_secret }}"
    tags: "{{ az_tags_dict }}"
    resource_group: "{{ app_location_id }}-{{ app_subscription_id }}-{{ app_environment_id }}-Rsg-{{ app_description }}-{{ app_increment }}"
    location: "{{ app_rsg_location }}"
    state: "present"
    name: "{{ vm_item.name }}{{ '%02d'|format(index +1|int) }}"
    vm_size: "{{ vm_item.az_vm_size }}"
    managed_disk_type: Standard_LRS
    network_interface_names: "{{ vm_item.name }}-nic-{{ '%02d'|format(index +1|int) }}"
    admin_username: "{{ vm_item.vm_admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys: 
      - path: "/home/{{ vm_item.vm_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ vm_item.vm_admin_public_key }}"
    image:
      offer: "{{ vm_item.image_offer }}"
      publisher: "{{ vm_item.image_publisher }}"
      sku: "{{ vm_item.image_sku }}"
      version: "{{ vm_item.image_version }}"
  register: CreatedVirtualMachine

- name: Add Virtual Machine into Host
  add_host:
    name: new_azure_vm
    ansible_host: '{{ CreatedVirtualMachine.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}'

- name: wait for the SSH port to come online
  wait_for:
    port: 22
    host: '{{ CreatedVirtualMachine.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress }}'
    timeout: 600

- block:
  - name: Applying CIS Benchmarking Configuration
    become: true
    include_role: ansible-rhel7-cis-benchmarks
  delegate_to: new_azure_vm
...
